backend:
  name: github
  repo: desategongan2025/desategongan2025.github.io  # Ganti dengan repo kamu
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Berita"
    folder: "posts"  # Folder tempat konten disimpan
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Judul" }
      - { name: "date", label: "Tanggal", widget: "datetime" }
      - { name: "body", label: "Isi Berita", widget: "markdown" }
