backend:
  name: github
  repo: desategongan2025/web-desa  # ganti sesuai repo kamu

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Berita"
    folder: "posts"   # kita pakai folder posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Konten", name: "body", widget: "markdown"}
