backend:
  name: github
  repo: username/nama-repo  # Ganti dengan repo kamu
  branch: main  # Atau master jika pakai master
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: https://desategongan2025.github.io


media_folder: "images/uploads" # Folder untuk gambar
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"  # Folder tempat file konten
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
